#!/bin/zsh

get_branch_name() {
    git symbolic-ref --short -q HEAD
}

get_jira_issue() {
    local branch_name=`get_branch_name`
    [[ $branch_name =~ '[a-z]*\/([A-Z]+-[0-9]+)' ]] && echo $match[1]
}


main() {
    local message="$1"
    local jira_issue=`get_jira_issue`

    [[ -n $jira_issue ]] && message="$jira_issue - $message"

    git commit -m "$message"
}

main "$1"
